// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: b8d375e642
// Version Date: Fri Aug 4 23:55:38 UTC 2017

package handlers

import (
	pb "github.com/myambition/ambition/services/rello/rello-service"
)

// CheckListWebhook implements Service.
func CheckListWebhook(ModelCheckListWebhook pb.Model, ActionCheckListWebhook pb.Action) (*pb.ChecklistUpdate, error) {
	request := pb.ChecklistUpdate{
		Model:  &ModelCheckListWebhook,
		Action: &ActionCheckListWebhook,
	}
	return &request, nil
}

// EmptyRPC implements Service.
func EmptyRPC() (*pb.Empty, error) {
	request := pb.Empty{}
	return &request, nil
}
