sudo: true
dist: trusty

language: go

go:
  - 1.8.x

go_import_path: github.com/myambition/ambition

jobs:
  include:
    - stage: test
      script:
        - go build -v github.com/myambition/ambition/...
    - stage: build and deploy
      branches:
        only:
          - master
      script:
        - echo true

notifications:
  email: false
