// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: b8d375e642
// Version Date: Fri Aug 4 23:55:38 UTC 2017

// Package grpc provides a gRPC client for the Rello service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/myambition/ambition/services/rello/rello-service"
	"github.com/myambition/ambition/services/rello/rello-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.RelloServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var checklistwebhookEndpoint endpoint.Endpoint
	{
		checklistwebhookEndpoint = grpctransport.NewClient(
			conn,
			"rello.Rello",
			"CheckListWebhook",
			EncodeGRPCCheckListWebhookRequest,
			DecodeGRPCCheckListWebhookResponse,
			pb.Empty{},
			clientOptions...,
		).Endpoint()
	}

	var emptyrpcEndpoint endpoint.Endpoint
	{
		emptyrpcEndpoint = grpctransport.NewClient(
			conn,
			"rello.Rello",
			"EmptyRPC",
			EncodeGRPCEmptyRPCRequest,
			DecodeGRPCEmptyRPCResponse,
			pb.Empty{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		CheckListWebhookEndpoint: checklistwebhookEndpoint,
		EmptyRPCEndpoint:         emptyrpcEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCCheckListWebhookResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC checklistwebhook reply to a user-domain checklistwebhook response. Primarily useful in a client.
func DecodeGRPCCheckListWebhookResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Empty)
	return reply, nil
}

// DecodeGRPCEmptyRPCResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC emptyrpc reply to a user-domain emptyrpc response. Primarily useful in a client.
func DecodeGRPCEmptyRPCResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Empty)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCCheckListWebhookRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain checklistwebhook request to a gRPC checklistwebhook request. Primarily useful in a client.
func EncodeGRPCCheckListWebhookRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.ChecklistUpdate)
	return req, nil
}

// EncodeGRPCEmptyRPCRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain emptyrpc request to a gRPC emptyrpc request. Primarily useful in a client.
func EncodeGRPCEmptyRPCRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Empty)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
