// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: d5b3153b9f
// Version Date: Thu Jul 27 18:20:46 UTC 2017

package main

import (
	"flag"

	"github.com/myambition/ambition/internal/logger"

	// This Service

	"github.com/myambition/ambition/services/users/users-service/svc/server"
	"github.com/myambition/ambition/services/users/users-service/svc/server/cli"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	// Logging domain.
	server.Run(cli.Config, logger.Debug())
}
