// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: b8d375e642
// Version Date: Fri Aug 4 23:55:38 UTC 2017

package main

import (
	"flag"

	// This Service
	"github.com/myambition/ambition/services/model/model-service/svc/server"
	"github.com/myambition/ambition/services/model/model-service/svc/server/cli"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(cli.Config)
}
