// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: d5b3153b9f
// Version Date: Thu Jul 27 18:20:46 UTC 2017

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"golang.org/x/net/context"
	"google.golang.org/grpc"

	"github.com/pkg/errors"

	// This Service
	pb "github.com/adamryman/ambition/users/users-service"
	"github.com/adamryman/ambition/users/users-service/svc/client/cli/handlers"
	grpcclient "github.com/adamryman/ambition/users/users-service/svc/client/grpc"
	httpclient "github.com/adamryman/ambition/users/users-service/svc/client/http"
)

var (
	_ = strconv.ParseInt
	_ = strings.Split
	_ = json.Compact
	_ = errors.Wrapf
	_ = pb.RegisterUsersServer
)

func main() {
	os.Exit(submain())
}

type headerSeries []string

func (h *headerSeries) Set(val string) error {
	const requiredParts int = 2
	parts := strings.SplitN(val, ":", requiredParts)
	if len(parts) != requiredParts {
		return fmt.Errorf("value %q cannot be split in two; must contain at least one ':' character", val)
	}
	parts[1] = strings.TrimSpace(parts[1])
	*h = append(*h, parts...)
	return nil
}

func (h *headerSeries) String() string {
	return fmt.Sprintf("%v", []string(*h))
}

// submain exists to act as the functional main, but will return exit codes to
// the actual main instead of calling os.Exit directly. This is done to allow
// the defered functions to be called, since if os.Exit where called directly
// from this function, none of the defered functions set up by this function
// would be called.
func submain() int {
	var headers headerSeries
	flag.Var(&headers, "header", "Header(s) to be sent in the transport (follows cURL style)")
	var (
		httpAddr = flag.String("http.addr", "", "HTTP address of addsvc")
		grpcAddr = flag.String("grpc.addr", ":5040", "gRPC (HTTP) address of addsvc")
	)

	// The addcli presumes no service discovery system, and expects users to
	// provide the direct address of an service. This presumption is reflected in
	// the cli binary and the the client packages: the -transport.addr flags
	// and various client constructors both expect host:port strings.

	fsCreateUser := flag.NewFlagSet("createuser", flag.ExitOnError)

	fsDeleteUser := flag.NewFlagSet("deleteuser", flag.ExitOnError)

	fsReadUser := flag.NewFlagSet("readuser", flag.ExitOnError)

	fsUpdateUser := flag.NewFlagSet("updateuser", flag.ExitOnError)

	var (
		flagIDCreateUser     = fsCreateUser.Int64("id", 0, "")
		flagInfoCreateUser   = fsCreateUser.String("info", "", "")
		flagTrelloCreateUser = fsCreateUser.String("trello", "", "")
		flagIDReadUser       = fsReadUser.Int64("id", 0, "")
		flagInfoReadUser     = fsReadUser.String("info", "", "")
		flagTrelloReadUser   = fsReadUser.String("trello", "", "")
		flagIDUpdateUser     = fsUpdateUser.Int64("id", 0, "")
		flagInfoUpdateUser   = fsUpdateUser.String("info", "", "")
		flagTrelloUpdateUser = fsUpdateUser.String("trello", "", "")
		flagIDDeleteUser     = fsDeleteUser.Int64("id", 0, "")
		flagInfoDeleteUser   = fsDeleteUser.String("info", "", "")
		flagTrelloDeleteUser = fsDeleteUser.String("trello", "", "")
	)

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\n")
		fmt.Fprintf(os.Stderr, "Subcommands:\n")
		fmt.Fprintf(os.Stderr, "  %s\n", "createuser")
		fmt.Fprintf(os.Stderr, "  %s\n", "deleteuser")
		fmt.Fprintf(os.Stderr, "  %s\n", "readuser")
		fmt.Fprintf(os.Stderr, "  %s\n", "updateuser")
	}
	if len(os.Args) < 2 {
		flag.Usage()
		return 1
	}

	flag.Parse()

	var (
		service pb.UsersServer
		err     error
	)

	if *httpAddr != "" {
		service, err = httpclient.New(*httpAddr, httpclient.CtxValuesToSend(headers...))
	} else if *grpcAddr != "" {
		conn, err := grpc.Dial(*grpcAddr, grpc.WithInsecure(), grpc.WithTimeout(time.Second))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error while dialing grpc connection: %v", err)
			return 1
		}
		defer conn.Close()
		service, err = grpcclient.New(conn, grpcclient.CtxValuesToSend(headers...))
	} else {
		fmt.Fprintf(os.Stderr, "error: no remote address specified\n")
		return 1
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	if len(flag.Args()) < 1 {
		fmt.Printf("No 'method' subcommand provided; exiting.")
		flag.Usage()
		return 1
	}

	ctx := context.Background()
	for i := 0; i < len(headers); i += 2 {
		ctx = context.WithValue(ctx, headers[i], headers[i+1])
	}

	switch flag.Args()[0] {

	case "createuser":
		fsCreateUser.Parse(flag.Args()[1:])

		IDCreateUser := *flagIDCreateUser

		var InfoCreateUser pb.UserInfo
		if flagInfoCreateUser != nil && len(*flagInfoCreateUser) > 0 {
			err = json.Unmarshal([]byte(*flagInfoCreateUser), &InfoCreateUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling InfoCreateUser from %v:", flagInfoCreateUser))
			}
		}

		var TrelloCreateUser pb.TrelloInfo
		if flagTrelloCreateUser != nil && len(*flagTrelloCreateUser) > 0 {
			err = json.Unmarshal([]byte(*flagTrelloCreateUser), &TrelloCreateUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling TrelloCreateUser from %v:", flagTrelloCreateUser))
			}
		}

		request, err := handlers.CreateUser(IDCreateUser, InfoCreateUser, TrelloCreateUser)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling handlers.CreateUser: %v\n", err)
			return 1
		}

		v, err := service.CreateUser(ctx, request)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling service.CreateUser: %v\n", err)
			return 1
		}
		fmt.Println("Client Requested with:")
		fmt.Println(IDCreateUser, InfoCreateUser, TrelloCreateUser)
		fmt.Println("Server Responded with:")
		fmt.Println(v)

	case "deleteuser":
		fsDeleteUser.Parse(flag.Args()[1:])

		IDDeleteUser := *flagIDDeleteUser

		var InfoDeleteUser pb.UserInfo
		if flagInfoDeleteUser != nil && len(*flagInfoDeleteUser) > 0 {
			err = json.Unmarshal([]byte(*flagInfoDeleteUser), &InfoDeleteUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling InfoDeleteUser from %v:", flagInfoDeleteUser))
			}
		}

		var TrelloDeleteUser pb.TrelloInfo
		if flagTrelloDeleteUser != nil && len(*flagTrelloDeleteUser) > 0 {
			err = json.Unmarshal([]byte(*flagTrelloDeleteUser), &TrelloDeleteUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling TrelloDeleteUser from %v:", flagTrelloDeleteUser))
			}
		}

		request, err := handlers.DeleteUser(IDDeleteUser, InfoDeleteUser, TrelloDeleteUser)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling handlers.DeleteUser: %v\n", err)
			return 1
		}

		v, err := service.DeleteUser(ctx, request)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling service.DeleteUser: %v\n", err)
			return 1
		}
		fmt.Println("Client Requested with:")
		fmt.Println(IDDeleteUser, InfoDeleteUser, TrelloDeleteUser)
		fmt.Println("Server Responded with:")
		fmt.Println(v)

	case "readuser":
		fsReadUser.Parse(flag.Args()[1:])

		IDReadUser := *flagIDReadUser

		var InfoReadUser pb.UserInfo
		if flagInfoReadUser != nil && len(*flagInfoReadUser) > 0 {
			err = json.Unmarshal([]byte(*flagInfoReadUser), &InfoReadUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling InfoReadUser from %v:", flagInfoReadUser))
			}
		}

		var TrelloReadUser pb.TrelloInfo
		if flagTrelloReadUser != nil && len(*flagTrelloReadUser) > 0 {
			err = json.Unmarshal([]byte(*flagTrelloReadUser), &TrelloReadUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling TrelloReadUser from %v:", flagTrelloReadUser))
			}
		}

		request, err := handlers.ReadUser(IDReadUser, InfoReadUser, TrelloReadUser)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling handlers.ReadUser: %v\n", err)
			return 1
		}

		v, err := service.ReadUser(ctx, request)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling service.ReadUser: %v\n", err)
			return 1
		}
		fmt.Println("Client Requested with:")
		fmt.Println(IDReadUser, InfoReadUser, TrelloReadUser)
		fmt.Println("Server Responded with:")
		fmt.Println(v)

	case "updateuser":
		fsUpdateUser.Parse(flag.Args()[1:])

		IDUpdateUser := *flagIDUpdateUser

		var InfoUpdateUser pb.UserInfo
		if flagInfoUpdateUser != nil && len(*flagInfoUpdateUser) > 0 {
			err = json.Unmarshal([]byte(*flagInfoUpdateUser), &InfoUpdateUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling InfoUpdateUser from %v:", flagInfoUpdateUser))
			}
		}

		var TrelloUpdateUser pb.TrelloInfo
		if flagTrelloUpdateUser != nil && len(*flagTrelloUpdateUser) > 0 {
			err = json.Unmarshal([]byte(*flagTrelloUpdateUser), &TrelloUpdateUser)
			if err != nil {
				panic(errors.Wrapf(err, "unmarshalling TrelloUpdateUser from %v:", flagTrelloUpdateUser))
			}
		}

		request, err := handlers.UpdateUser(IDUpdateUser, InfoUpdateUser, TrelloUpdateUser)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling handlers.UpdateUser: %v\n", err)
			return 1
		}

		v, err := service.UpdateUser(ctx, request)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calling service.UpdateUser: %v\n", err)
			return 1
		}
		fmt.Println("Client Requested with:")
		fmt.Println(IDUpdateUser, InfoUpdateUser, TrelloUpdateUser)
		fmt.Println("Server Responded with:")
		fmt.Println(v)

	default:
		flag.Usage()
		return 1
	}

	return 0
}
